export type CountryCode = {
  code: string;
  name: string;
  nameEs: string;
};

export const countryCodes: CountryCode[] = [
  // Norteamérica
  { code: "+1", name: "United States / Canada", nameEs: "Estados Unidos / Canadá" },
  // El bloque +1 también incluye territorios caribeños y atlánticos
  { code: "+1-242", name: "Bahamas", nameEs: "Bahamas" },
  { code: "+1-246", name: "Barbados", nameEs: "Barbados" },
  { code: "+1-264", name: "Anguilla", nameEs: "Anguila" },
  { code: "+1-268", name: "Antigua and Barbuda", nameEs: "Antigua y Barbuda" },
  { code: "+1-284", name: "British Virgin Islands", nameEs: "Islas Vírgenes Británicas" },
  { code: "+1-345", name: "Cayman Islands", nameEs: "Islas Caimán" },
  { code: "+1-441", name: "Bermuda", nameEs: "Bermudas" },
  { code: "+1-473", name: "Grenada", nameEs: "Granada" },
  { code: "+1-649", name: "Turks and Caicos Islands", nameEs: "Islas Turcas y Caicos" },
  { code: "+1-664", name: "Montserrat", nameEs: "Montserrat" },
  { code: "+1-721", name: "Sint Maarten", nameEs: "San Martín (parte neerlandesa)" },
  { code: "+1-758", name: "Saint Lucia", nameEs: "Santa Lucía" },
  { code: "+1-767", name: "Dominica", nameEs: "Dominica" },
  { code: "+1-784", name: "Saint Vincent and the Grenadines", nameEs: "San Vicente y las Granadinas" },
  { code: "+1-787", name: "Puerto Rico", nameEs: "Puerto Rico" },
  { code: "+1-809", name: "Dominican Republic", nameEs: "República Dominicana" },
  { code: "+1-829", name: "Dominican Republic", nameEs: "República Dominicana" },
  { code: "+1-849", name: "Dominican Republic", nameEs: "República Dominicana" },
  { code: "+1-868", name: "Trinidad and Tobago", nameEs: "Trinidad y Tobago" },
  { code: "+1-869", name: "Saint Kitts and Nevis", nameEs: "San Cristóbal y Nieves" },
  { code: "+1-876", name: "Jamaica", nameEs: "Jamaica" },
  { code: "+1-939", name: "Puerto Rico", nameEs: "Puerto Rico" },

  // Latinoamérica
  { code: "+52", name: "Mexico", nameEs: "México" },
  { code: "+53", name: "Cuba", nameEs: "Cuba" },
  { code: "+54", name: "Argentina", nameEs: "Argentina" },
  { code: "+55", name: "Brazil", nameEs: "Brasil" },
  { code: "+56", name: "Chile", nameEs: "Chile" },
  { code: "+57", name: "Colombia", nameEs: "Colombia" },
  { code: "+58", name: "Venezuela", nameEs: "Venezuela" },
  { code: "+501", name: "Belize", nameEs: "Belice" },
  { code: "+502", name: "Guatemala", nameEs: "Guatemala" },
  { code: "+503", name: "El Salvador", nameEs: "El Salvador" },
  { code: "+504", name: "Honduras", nameEs: "Honduras" },
  { code: "+505", name: "Nicaragua", nameEs: "Nicaragua" },
  { code: "+506", name: "Costa Rica", nameEs: "Costa Rica" },
  { code: "+507", name: "Panama", nameEs: "Panamá" },
  { code: "+509", name: "Haiti", nameEs: "Haití" },
  { code: "+591", name: "Bolivia", nameEs: "Bolivia" },
  { code: "+592", name: "Guyana", nameEs: "Guyana" },
  { code: "+593", name: "Ecuador", nameEs: "Ecuador" },
  { code: "+594", name: "French Guiana", nameEs: "Guayana Francesa" },
  { code: "+595", name: "Paraguay", nameEs: "Paraguay" },
  { code: "+596", name: "Martinique", nameEs: "Martinica" },
  { code: "+597", name: "Suriname", nameEs: "Surinam" },
  { code: "+598", name: "Uruguay", nameEs: "Uruguay" },

  // Europa
  { code: "+30", name: "Greece", nameEs: "Grecia" },
  { code: "+31", name: "Netherlands", nameEs: "Países Bajos" },
  { code: "+32", name: "Belgium", nameEs: "Bélgica" },
  { code: "+33", name: "France", nameEs: "Francia" },
  { code: "+34", name: "Spain", nameEs: "España" },
  { code: "+36", name: "Hungary", nameEs: "Hungría" },
  { code: "+39", name: "Italy", nameEs: "Italia" },
  { code: "+40", name: "Romania", nameEs: "Rumania" },
  { code: "+41", name: "Switzerland", nameEs: "Suiza" },
  { code: "+43", name: "Austria", nameEs: "Austria" },
  { code: "+44", name: "United Kingdom", nameEs: "Reino Unido" },
  { code: "+45", name: "Denmark", nameEs: "Dinamarca" },
  { code: "+46", name: "Sweden", nameEs: "Suecia" },
  { code: "+47", name: "Norway", nameEs: "Noruega" },
  { code: "+48", name: "Poland", nameEs: "Polonia" },
  { code: "+49", name: "Germany", nameEs: "Alemania" },
  { code: "+350", name: "Gibraltar", nameEs: "Gibraltar" },
  { code: "+351", name: "Portugal", nameEs: "Portugal" },
  { code: "+352", name: "Luxembourg", nameEs: "Luxemburgo" },
  { code: "+353", name: "Ireland", nameEs: "Irlanda" },
  { code: "+354", name: "Iceland", nameEs: "Islandia" },
  { code: "+355", name: "Albania", nameEs: "Albania" },
  { code: "+356", name: "Malta", nameEs: "Malta" },
  { code: "+357", name: "Cyprus", nameEs: "Chipre" },
  { code: "+358", name: "Finland", nameEs: "Finlandia" },
  { code: "+359", name: "Bulgaria", nameEs: "Bulgaria" },
  { code: "+370", name: "Lithuania", nameEs: "Lituania" },
  { code: "+371", name: "Latvia", nameEs: "Letonia" },
  { code: "+372", name: "Estonia", nameEs: "Estonia" },
  { code: "+373", name: "Moldova", nameEs: "Moldavia" },
  { code: "+374", name: "Armenia", nameEs: "Armenia" },
  { code: "+375", name: "Belarus", nameEs: "Bielorrusia" },
  { code: "+376", name: "Andorra", nameEs: "Andorra" },
  { code: "+377", name: "Monaco", nameEs: "Mónaco" },
  { code: "+378", name: "San Marino", nameEs: "San Marino" },
  { code: "+380", name: "Ukraine", nameEs: "Ucrania" },
  { code: "+381", name: "Serbia", nameEs: "Serbia" },
  { code: "+382", name: "Montenegro", nameEs: "Montenegro" },
  { code: "+383", name: "Kosovo", nameEs: "Kosovo" },
  { code: "+385", name: "Croatia", nameEs: "Croacia" },
  { code: "+386", name: "Slovenia", nameEs: "Eslovenia" },
  { code: "+387", name: "Bosnia and Herzegovina", nameEs: "Bosnia y Herzegovina" },
  { code: "+389", name: "North Macedonia", nameEs: "Macedonia del Norte" },
  { code: "+420", name: "Czech Republic", nameEs: "República Checa" },
  { code: "+421", name: "Slovakia", nameEs: "Eslovaquia" },
  { code: "+423", name: "Liechtenstein", nameEs: "Liechtenstein" },

  // Asia
  { code: "+7", name: "Russia / Kazakhstan", nameEs: "Rusia / Kazajistán" },
  { code: "+81", name: "Japan", nameEs: "Japón" },
  { code: "+82", name: "South Korea", nameEs: "Corea del Sur" },
  { code: "+84", name: "Vietnam", nameEs: "Vietnam" },
  { code: "+86", name: "China", nameEs: "China" },
  { code: "+90", name: "Turkey", nameEs: "Turquía" },
  { code: "+91", name: "India", nameEs: "India" },
  { code: "+92", name: "Pakistan", nameEs: "Pakistán" },
  { code: "+93", name: "Afghanistan", nameEs: "Afganistán" },
  { code: "+94", name: "Sri Lanka", nameEs: "Sri Lanka" },
  { code: "+95", name: "Myanmar", nameEs: "Myanmar" },
  { code: "+98", name: "Iran", nameEs: "Irán" },
  { code: "+60", name: "Malaysia", nameEs: "Malasia" },
  { code: "+61", name: "Australia", nameEs: "Australia" },
  { code: "+62", name: "Indonesia", nameEs: "Indonesia" },
  { code: "+63", name: "Philippines", nameEs: "Filipinas" },
  { code: "+64", name: "New Zealand", nameEs: "Nueva Zelanda" },
  { code: "+65", name: "Singapore", nameEs: "Singapur" },
  { code: "+66", name: "Thailand", nameEs: "Tailandia" },
  { code: "+670", name: "East Timor", nameEs: "Timor Oriental" },
  { code: "+673", name: "Brunei", nameEs: "Brunéi" },
  { code: "+674", name: "Nauru", nameEs: "Nauru" },
  { code: "+675", name: "Papua New Guinea", nameEs: "Papúa Nueva Guinea" },
  { code: "+676", name: "Tonga", nameEs: "Tonga" },
  { code: "+677", name: "Solomon Islands", nameEs: "Islas Salomón" },
  { code: "+678", name: "Vanuatu", nameEs: "Vanuatu" },
  { code: "+679", name: "Fiji", nameEs: "Fiyi" },
  { code: "+680", name: "Palau", nameEs: "Palaos" },
  { code: "+681", name: "Wallis and Futuna", nameEs: "Wallis y Futuna" },
  { code: "+682", name: "Cook Islands", nameEs: "Islas Cook" },
  { code: "+683", name: "Niue", nameEs: "Niue" },
  { code: "+685", name: "Samoa", nameEs: "Samoa" },
  { code: "+686", name: "Kiribati", nameEs: "Kiribati" },
  { code: "+687", name: "New Caledonia", nameEs: "Nueva Caledonia" },
  { code: "+688", name: "Tuvalu", nameEs: "Tuvalu" },
  { code: "+689", name: "French Polynesia", nameEs: "Polinesia Francesa" },
  { code: "+690", name: "Tokelau", nameEs: "Tokelau" },
  { code: "+691", name: "Micronesia", nameEs: "Micronesia" },
  { code: "+692", name: "Marshall Islands", nameEs: "Islas Marshall" },
  { code: "+850", name: "North Korea", nameEs: "Corea del Norte" },
  { code: "+852", name: "Hong Kong", nameEs: "Hong Kong" },
  { code: "+853", name: "Macau", nameEs: "Macao" },
  { code: "+855", name: "Cambodia", nameEs: "Camboya" },
  { code: "+856", name: "Laos", nameEs: "Laos" },
  { code: "+880", name: "Bangladesh", nameEs: "Bangladesh" },
  { code: "+886", name: "Taiwan", nameEs: "Taiwán" },
  { code: "+960", name: "Maldives", nameEs: "Maldivas" },
  { code: "+961", name: "Lebanon", nameEs: "Líbano" },
  { code: "+962", name: "Jordan", nameEs: "Jordania" },
  { code: "+963", name: "Syria", nameEs: "Siria" },
  { code: "+964", name: "Iraq", nameEs: "Irak" },
  { code: "+965", name: "Kuwait", nameEs: "Kuwait" },
  { code: "+966", name: "Saudi Arabia", nameEs: "Arabia Saudita" },
  { code: "+967", name: "Yemen", nameEs: "Yemen" },
  { code: "+968", name: "Oman", nameEs: "Omán" },
  { code: "+970", name: "Palestine", nameEs: "Palestina" },
  { code: "+971", name: "United Arab Emirates", nameEs: "Emiratos Árabes Unidos" },
  { code: "+972", name: "Israel", nameEs: "Israel" },
  { code: "+973", name: "Bahrain", nameEs: "Baréin" },
  { code: "+974", name: "Qatar", nameEs: "Catar" },
  { code: "+975", name: "Bhutan", nameEs: "Bután" },
  { code: "+976", name: "Mongolia", nameEs: "Mongolia" },
  { code: "+977", name: "Nepal", nameEs: "Nepal" },
  { code: "+992", name: "Tajikistan", nameEs: "Tayikistán" },
  { code: "+993", name: "Turkmenistan", nameEs: "Turkmenistán" },
  { code: "+994", name: "Azerbaijan", nameEs: "Azerbaiyán" },
  { code: "+995", name: "Georgia", nameEs: "Georgia" },
  { code: "+996", name: "Kyrgyzstan", nameEs: "Kirguistán" },
  { code: "+998", name: "Uzbekistan", nameEs: "Uzbekistán" },

  // África
  { code: "+20", name: "Egypt", nameEs: "Egipto" },
  { code: "+27", name: "South Africa", nameEs: "Sudáfrica" },
  { code: "+211", name: "South Sudan", nameEs: "Sudán del Sur" },
  { code: "+212", name: "Morocco", nameEs: "Marruecos" },
  { code: "+213", name: "Algeria", nameEs: "Argelia" },
  { code: "+216", name: "Tunisia", nameEs: "Túnez" },
  { code: "+218", name: "Libya", nameEs: "Libia" },
  { code: "+220", name: "Gambia", nameEs: "Gambia" },
  { code: "+221", name: "Senegal", nameEs: "Senegal" },
  { code: "+222", name: "Mauritania", nameEs: "Mauritania" },
  { code: "+223", name: "Mali", nameEs: "Malí" },
  { code: "+224", name: "Guinea", nameEs: "Guinea" },
  { code: "+225", name: "Ivory Coast", nameEs: "Costa de Marfil" },
  { code: "+226", name: "Burkina Faso", nameEs: "Burkina Faso" },
  { code: "+227", name: "Niger", nameEs: "Níger" },
  { code: "+228", name: "Togo", nameEs: "Togo" },
  { code: "+229", name: "Benin", nameEs: "Benín" },
  { code: "+230", name: "Mauritius", nameEs: "Mauricio" },
  { code: "+231", name: "Liberia", nameEs: "Liberia" },
  { code: "+232", name: "Sierra Leone", nameEs: "Sierra Leona" },
  { code: "+233", name: "Ghana", nameEs: "Ghana" },
  { code: "+234", name: "Nigeria", nameEs: "Nigeria" },
  { code: "+235", name: "Chad", nameEs: "Chad" },
  { code: "+236", name: "Central African Republic", nameEs: "República Centroafricana" },
  { code: "+237", name: "Cameroon", nameEs: "Camerún" },
  { code: "+238", name: "Cape Verde", nameEs: "Cabo Verde" },
  { code: "+239", name: "São Tomé and Príncipe", nameEs: "Santo Tomé y Príncipe" },
  { code: "+240", name: "Equatorial Guinea", nameEs: "Guinea Ecuatorial" },
  { code: "+241", name: "Gabon", nameEs: "Gabón" },
  { code: "+242", name: "Republic of the Congo", nameEs: "República del Congo" },
  { code: "+243", name: "DR Congo", nameEs: "República Democrática del Congo" },
  { code: "+244", name: "Angola", nameEs: "Angola" },
  { code: "+245", name: "Guinea-Bissau", nameEs: "Guinea-Bisáu" },
  { code: "+248", name: "Seychelles", nameEs: "Seychelles" },
  { code: "+249", name: "Sudan", nameEs: "Sudán" },
  { code: "+250", name: "Rwanda", nameEs: "Ruanda" },
  { code: "+251", name: "Ethiopia", nameEs: "Etiopía" },
  { code: "+252", name: "Somalia", nameEs: "Somalia" },
  { code: "+253", name: "Djibouti", nameEs: "Yibuti" },
  { code: "+254", name: "Kenya", nameEs: "Kenia" },
  { code: "+255", name: "Tanzania", nameEs: "Tanzania" },
  { code: "+256", name: "Uganda", nameEs: "Uganda" },
  { code: "+257", name: "Burundi", nameEs: "Burundi" },
  { code: "+258", name: "Mozambique", nameEs: "Mozambique" },
  { code: "+260", name: "Zambia", nameEs: "Zambia" },
  { code: "+261", name: "Madagascar", nameEs: "Madagascar" },
  { code: "+262", name: "Réunion", nameEs: "Reunión" },
  { code: "+263", name: "Zimbabwe", nameEs: "Zimbabue" },
  { code: "+264", name: "Namibia", nameEs: "Namibia" },
  { code: "+265", name: "Malawi", nameEs: "Malaui" },
  { code: "+266", name: "Lesotho", nameEs: "Lesoto" },
  { code: "+267", name: "Botswana", nameEs: "Botsuana" },
  { code: "+268", name: "Eswatini", nameEs: "Esuatini" },
  { code: "+269", name: "Comoros", nameEs: "Comoras" },
  { code: "+290", name: "Saint Helena", nameEs: "Santa Elena" },
  { code: "+291", name: "Eritrea", nameEs: "Eritrea" },
];

export const DEFAULT_COUNTRY_CODE = "+34";